apiVersion: apps/v1
kind: Deployment
metadata:
  name: elastic-layer-deploy
  labels:
    app: elastic-layer
spec:

  replicas: 3
  selector:
    matchLabels:
      app: elastic-layer

  template:
    metadata:
      labels:
        app: elastic-layer

    spec:
    
      containers:
        - name: elastic-layer
          image: charliewager/flask_elastic_layer
          ports:
            - containerPort: 4500
          env:
            - name: RDS_USERNAME
              value: postgres

            - name: RDS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: superUserPassword

            - name: RDS_HOSTNAME-PRIMARY
              value: vikegres

            - name: RDS_HOSTNAME-REPLICA
              value: vikegres-replica

            - name: RDS_PORT
              value: '5432'
              
            - name: RDS_DB_NAME
              value: vike_and_sell_db

          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "1"