apiVersion: apps/v1
kind: Deployment
metadata:
  name: elastic-layer-deploy
  labels:
    app: elastic-layer
spec:

  replicas: 1
  selector:
    matchLabels:
      app: elastic-layer

  template:
    metadata:
      labels:
        app: elastic-layer

    spec:

      containers:
      - name: elastic-layer
        image: charliewager/flask_elastic_layer:v11
        ports:
        - containerPort: 4500
        env:
        - name: ELASTIC_PASSWORD
          valueFrom:
            secretKeyRef:
              name: elasticsearch-master-credentials
              key: password

        - name: DATA_URL
          value: data-layer-cluster-ip:80

        - name: DATA_API_KEY
          valueFrom:
            secretKeyRef:
              name: vs-api-key
              key: API_KEY

        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "1"

        imagePullPolicy: Always
