apiVersion: apps/v1
kind: Deployment
metadata:
  name: elastic-layer-deploy
  labels:
    app: elastic-layer
spec:

  replicas: 3
  selector:
    matchLabels:
      app: elastic-layer

  template:
    metadata:
      labels:
        app: elastic-layer

    spec:

      containers:
      - name: elastic-layer
        image: charliewager/flask_elastic_layer
        ports:
        - containerPort: 4500
        env:
        - name: ELASTIC_PASSWORD
          value: postgres

        - name: DATALAYER_HOST
          value: 10.152.183.106:80

        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "1"
