apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgsync-deploy
  labels:
    app: pgsync

spec:

  replicas: 1
  selector:
    matchLabels:
      app: pgsync

  template:
    metadata:
      labels:
        app: pgsync

    spec:

      containers:
      - name: pgsync
        image: charliewager/pgsync:v4

        # all envs located in .env file

        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        imagePullPolicy: Always
