apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgsync-deploy
  labels:
    app: pgsync

spec:

  replicas: 1
  selector:
    matchLabels:
      app: pgsync

  template:
    metadata:
      labels:
        app: pgsync

    spec:

      containers:
      - name: pgsync
        image: charliewager/pgsync:v18

        env:
        - name: PG_USER
          value: postgres

        - name: PG_HOST
          value: vikegres

        - name: PG_PORT
          value: '5432'

        - name: PG_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: superUserPassword

        - name: LOG_LEVEL
          value: "INFO"

        - name: ELASTICSEARCH_PORT
          value: '9200'

        - name: ELASTICSEARCH_SCHEME
          value: "http"

        - name: ELASTICSEARCH_HOST
          value: elasticsearch-master

        - name: REDIS_HOST
          value: redis

        - name: REDIS_PORT
          value: '6379'

        - name: ELASTICSEARCH
          value: "true"

        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        imagePullPolicy: Always
